name: Tests & Lint

on:
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  libChanges:
    name: Check Affected Libraries
    runs-on: ubuntu-latest
    outputs:
      changed_projects: ${{ steps.check_changes.outputs.changed_projects }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check the changes
        id: check_changes
        run: |
          # get the projects "root" key from the angular.json file
          PROJECTS_STR=$(cat angular.json | jq -r '.projects[] | select (.architect.test) | .root')
          
          # split the string with '\n' as delimiter to create an array
          array=($PROJECTS_STR)
          
          for element in "${array[@]}"; do
          echo "wef $element"
          done
          
          CHANGED_PROJECTS=()
          
          for p in $array; do
            echo "Checking changes for $p"
            if git diff --diff-filter=MA --name-only origin/${{ github.base_ref }}..origin/${{ github.head_ref }} | grep "$p"; then
            CHANGED_PROJECTS+=("$p")
            fi
          done
          
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_OUTPUT
      
  # HumaUtils library tests
  # test-huma-utils:
  #   name: "Unit Tests: Utils Library"
  #   if: needs.libChanges.outputs.utils_changes != ''
  #   needs: [dependencies, libChanges]
  #   uses: ./.github/workflows/library-unit-tests.yaml
  #   with:
  #     library: huma-utils
  #     cacheName: cache-node-modules
